ALTER TABLE car ADD COLUMN IF NOT EXISTS plate_number VARCHAR(20) UNIQUE;
ALTER TABLE bike ADD COLUMN IF NOT EXISTS bike_type VARCHAR(30) DEFAULT 'mountain';
ALTER TABLE boat RENAME COLUMN berth_number TO dock_number;
ALTER TABLE motorbike ALTER COLUMN engine_cc TYPE BIGINT;
